"""updated tables

Revision ID: 425158ed680f
Revises: 5123f4801374
Create Date: 2023-06-15 11:05:50.479817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '425158ed680f'
down_revision = '5123f4801374'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('birds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('birds', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
